mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls')),
    path('', include('landing_pages.urls')),
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/users/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name ='register'),
    path('edit_profile/', views.ProfileEditView.as_view(), name ='edit_profile'),
    path('login', views.LoginView.as_view(), name ='login'),
    path('password_reset', views.ResetPasswordView.as_view(), name ='password_reset'),
    path('password_rest_subject', views.ResetPasswordView.as_view(), name ='password_reset_subject'),
    path('password_reset_confirm/<uidb64>/<token>/',
        views.PasswordResetView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/',views.PasswordResetView.as_view(),name='password_reset_complete'),
    path('logout', views.logout_view, name ='logout'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('create_poll_name/', views.CreatePollView.as_view(), name ='create_poll_name'),
    path('edit_poll_name/<int:pk>/', views.EditPollView.as_view(), name ='edit_poll_name'),
    path('delete_poll_name/<int:pk>/', views.PollDeleteView.as_view(), name ='delete_poll_name'),
    path('create_poll_quiz/<int:poll_id>/', views.CreateQuizView.as_view(), name ='create_poll_quiz'),
    path('edit_questions/<int:pk>/', views.EditQuizView.as_view(), name ='edit_questions'),
    path('delete_question/<int:pk>/', views.QuizDeleteView.as_view(), name ='delete_question'),
    path('create_poll_choice/<int:question_id>/', views.CreateChoicesView.as_view(), name ='create_poll_choice'),
    path('available_polls/', views.AvailablePollsView.as_view(), name ='available_polls'),
    # path('searched/', views.SearchViews.as_view(), name ='searched'),
    path('available_questions/', views.AvailableQuestionsView.as_view(), name ='available_questions'),
    path('voters', views.VotersView.as_view(), name ='voters'),
    path('pollsearch/', views.PollsSearch.as_view(), name='pollsearch'),
    path('quizsearch/', views.QuizSearch.as_view(), name='quizsearch'),
    path('votersearch/', views.VoterSearch.as_view(), name='votersearch'),

]

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from polls.models import Poll, Question, Choice


class MemberForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

# class ChangePasswordForm(UserCreationForm):
#     old_password = forms.CharField(widget=forms.PasswordInput())
#     new_password = forms.CharField(widget=forms.PasswordInput())
#     confirm_password = forms.CharField(widget=forms.PasswordInput())

class CreatePollForm(ModelForm):
    name = forms.CharField(required=True)
    class Meta:
        model = Poll
        fields = ['name','posted_by']

class CreatePollQuizForm(ModelForm):
    pub_date = forms.DateTimeField(required=False)
    class Meta:
        model = Question
        fields = ['question_text','pub_date']

class CreatePollChoicesForm(ModelForm):
    question = forms.CharField(required=False)
    poll = forms.CharField(required=False)
    class Meta:
        model = Choice
        fields = ['choice_text']

mysite/users/views.py
from django.forms import BaseModelForm
from django.views.generic.edit import UpdateView
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import F, Count
from django.http import HttpResponse, HttpResponseRedirect
from polls.models import Choice, Question, Vote, Poll
from django.views import generic
from django.core.paginator import Paginator
from django.views.generic import FormView ,CreateView, ListView
from django.views.generic.edit import DeleteView
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserChangeForm
from users.forms import MemberForm, CreatePollForm, CreatePollQuizForm, CreatePollChoicesForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.signals import user_logged_in
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView
from django.conf import settings
from django.db.models import Q
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash, get_user_model


# Create your views here.
class RegisterView(generic.CreateView):
    form_class = MemberForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('polls:index')

    
class ProfileEditView(UpdateView):
    form_class = UserChangeForm
    template_name = 'users/edit_profile.html'
    success_url = reverse_lazy('users:login')

    def get_object(self):
        return self.request.user
    

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users:login')

class ChangePasswordView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/change_password.html'

class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('users:create_poll_name')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(self.request, username=username, password= password)
        if user is not None:
            login(self.request,user)
            messages.success(self.request, f'Welcome {username}')
            # redirect to a success page
            return redirect('users:create_poll_name')
        return render(self.request, "users/login.html")

def logout_view(request):
    logout(request)
    messages.success(request, f'You were Logged Out')
    return redirect('users:login')


class CreatePollView(LoginRequiredMixin,CreateView):
    form_class = CreatePollForm
    template_name = 'users/create_poll_name.html'
    
    def form_valid(self, form):
        obj = form.save()
        messages.success(self.request, f'Your Poll was added succcesfully')
        # success_url = reverse_lazy('users:create_poll_quiz', kwargs={'poll_id': obj.id})
        # return redirect (success_url)
        return super().form_valid(form)
    
    def get_success_url(self, **kwargs):
        success_url = reverse_lazy('users:create_poll_quiz',
                                    kwargs={'poll_id': self.object.id})
        return success_url

class EditPollView(UpdateView):
    model = Poll
    fields = ["name"]
    template_name = "users/edit_poll_name.html" 
    success_url = reverse_lazy('users:available_polls')



class PollDeleteView(DeleteView):
    model =Poll
    template_name = "users/delete_poll_name.html" 
    success_url = reverse_lazy("users:available_polls")



  
class CreateQuizView(LoginRequiredMixin,CreateView):
    form_class = CreatePollQuizForm
    template_name = 'users/create_poll_quiz.html'
    def form_valid(self, form):
        obj = form.save() 
        messages.success(self.request, f'Your Question was added succcesfully')
        #success_url = reverse_lazy('users:create_poll_choice', kwargs={'question_id': obj.id})
        # success_url = f'/create_poll_quiz/{obj.id}/'
        # return redirect (success_url)
        return super().form_valid(form)
    def get_success_url(self, **kwargs):
        success_url = reverse_lazy('users:create_poll_choice',
                                    kwargs={'question_id': self.object.id})
        return success_url
    
class EditQuizView(UpdateView):
    fields = ["question_text"]
    template_name = "users/edit_questions.html" 
    success_url = reverse_lazy('users:available_questions')
    queryset = Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")


class QuizDeleteView(DeleteView):
    model = Question
    template_name = "users/delete_question.html" 
    success_url = reverse_lazy("users:available_questions")


class CreateChoicesView(LoginRequiredMixin,CreateView):
    form_class = CreatePollChoicesForm
    template_name = 'users/create_poll_choice.html'
    success_url = reverse_lazy('polls:index')
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.question_id = self.kwargs.get('question_id')
        obj.save()
        messages.success(self.request, f'Your Choice was added succcesfully')
        return super().form_valid(form)

class AvailablePollsView(LoginRequiredMixin, ListView):
    form_class = CreatePollForm
    paginate_by= 4
    template_name = 'users/available_polls.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["polls"] = Poll.objects.all()
        context["count"] = Poll.objects.count()
        return context
    def get_queryset(self):
        search_query = self.request.GET.get("search_poll")
        if search_query:
            object_list = Poll.objects.filter(
                name__icontains=search_query).order_by("-pub_date")
        else:
            object_list = Poll.objects.all()
        return object_list
    
class AvailableQuestionsView(LoginRequiredMixin, ListView):
    form_class = CreatePollForm
    paginate_by = 4
    model = Question
    template_name = 'users/available_questions.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["questions"] = Question.objects.all()
        return context
    def get_queryset(self):  # new
        search_query = self.request.GET.get("search_quiz")
        if search_query:
            object_list = Question.objects.filter(
                question_text__icontains=search_query).order_by('-pub_date')
        else:
            object_list = Question.objects.all()
        return object_list
    
class VotersView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Poll
    template_name = "users/voters.html"
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the Users
        # context["voters"] = Poll.objects.all()
        user = get_user_model()
        context["users"] = user.objects.all()
        context["votes"] = Vote.objects.annotate(Count('voter'))
        return context
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class PollsSearch(LoginRequiredMixin, ListView):
    model = Poll
    template_name = 'users/available_polls.html'
    context_object_name = 'polls'

    def get_queryset(self):  # new
        search_query = self.request.GET.get("search_poll")
        if search_query:
            object_list = Poll.objects.filter(
                Q(name__icontains=search_query) | Q(id__icontains=search_query)) 
        else:
            object_list = Poll.objects.all()
        return object_list

class QuizSearch(LoginRequiredMixin, ListView):
    model = Question
    template_name = 'users/available_questions.html'
    context_object_name = 'questions'

    def get_queryset(self):  # new
        search_query = self.request.GET.get("search_quiz")
        if search_query:
            object_list = Question.objects.filter(
                Q(question_text__icontains=search_query) | Q(id__icontains=search_query))
        else:
            object_list = Question.objects.all()
        return object_list
    
class VoterSearch(LoginRequiredMixin, ListView):
    model = Poll
    template_name = 'users/voters.html'
    context_object_name = 'users'
    def get_queryset(self):
        search_query = self.request.GET.get("search_voter") 
        user = get_user_model()   
        if search_query:
            object_list = user.objects.filter(
            Q(first_name__icontains=search_query) | Q(last_name__icontains=search_query) | Q(email__icontains=search_query))
        else:
            object_list = user.objects.all()
        print(object_list)
        return object_list

    

mysite/users/templates/users/available_polls.html
{% extends 'base.html' %}

{% block content%}
<div class="card-header mb-3 mt-3">Pick a Poll: Add a question
  <div class="text-success">Total Polls: {{count}}</div>
</div>
<form action="{% url 'users:pollsearch' %}" class="d-flex mb-2" method="GET">
  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_poll">
  <button class="btn btn-outline-success" type="submit">Search</button>
</form>

<div class="row row-cols-1 row-cols-md-1 g-4">
  {% for poll in polls %}
  <div class="col">
    <div class="card border-success">
      <div class="card-body">
        <div class="card-header text-success mb-2">Poll ID: {{poll.id}}</div>
        <h5 class="card-title mt-2">
          <a href="{% url 'users:create_poll_quiz' poll.id%}" class="btn btn-primary btn-sm">{{poll.name}}</a>
          <div class="mt-3">
            <a href="{%url 'users:edit_poll_name' poll.id %}" class="btn btn-primary btn-sm">Edit Poll</a>
            <a href="{%url 'users:delete_poll_name' poll.pk%}" class="btn btn-primary btn-sm">Delete Poll</a>
          </div>
        </h5>
      </div>
      <div class="card-footer bg-transparent border-success">
        <p class="card-text"><small class="text-muted">Last update: {{poll.pub_date}}</small></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{%endblock%}

mysite/users/templates/users/available_questions.html
{% extends 'base.html' %}

{% block content%}

<div class="text-center">
  <div class="card-header mb-3 mt-3">Pick a question: Add a choice</div>
</div>
<form action="{% url 'users:quizsearch' %}" method="GET" class="d-flex mb-2">
  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"  name="search_quiz">
  <button class="btn btn-outline-success" type="submit">Search</button>
</form>
<div class="row row-cols-1 row-cols-md-1 g-4">
    {% for question in questions %}
    <div class="col">
      <div class="card border-success">
        <div class="card-body">
            <div class="card-header text-success ">Question ID: {{question.id}}
            </div>
            
          <h5 class="card-title mt-2">
            <a href="{% url 'users:create_poll_choice' question.id%}"
            class="btn btn-primary btn-sm">{{question.question_text}}</a>
            <div class="mt-3">
              <a href="{% url 'users:edit_questions' question.pk%}"
              class="btn btn-primary btn-sm">Edit Question</a>
              <a href="{% url 'users:delete_question' question.pk%}"
              class="btn btn-primary btn-sm">Delete Question</a>
            </div>

          </h5>
        </div>
        <div class="card-footer bg-transparent border-success">
            <p class="card-text"><small class="text-muted">Last update: {{question.pub_date}}</small></p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{%endblock%}

mysite/users/templates/users/change_password.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="card border-warning mb-3 mt-4" style="width: 30rem;">
  <div class="card-body">
    <div class="card-header border-warning mb-3">Change Password</div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn-success">Save changes</button>
      <div class="card-footer border-warning mt-3">
        <small class="text-muted">
          <a href="{% url 'users:login'%}" class="card-link">Back to login <span style='font-size:20px;'>&#128072;</span></a>
        </small>
      </div>
    </form>
  </div>
</div>
{% endblock %}

mysite/users/templates/users/create_poll_choice.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Create Poll{% endblock %}
{% block content %}
{{form.errors}}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create A New Poll</h3>
            </div>
            <form action="" method="POST">
              {% csrf_token %}
                <div class="panel-body">
                    <div class="row"> 
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="choice_text">Choice</label>
                                {% render_field form.choice_text rows="3" class="form-control" required=True %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <hr />
                        <div class="col-lg-4">
                            <button type="submit" class="btn btn-info">Submit</button>
                            <a href="{% url 'users:available_polls'%}" class="btn btn-info ">Available Polls</a>
                            <a href="{% url 'users:available_questions' %}" class="btn btn-info ">Available questions</a>

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mysite/users/templates/users/create_poll_name.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Create Poll{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create A New Poll</h3>
            </div>
            <form action="" method="POST">
              {% csrf_token %}
                <div class="panel-body">
                    <div class="row">
                            <div class="form-group">
                                <label for="name">Poll Title</label>
                                {% render_field form.name class="form-control" %}
                            </div>
                        </div>
                        
                    <div class="row">
                        <div class="col mb-2 mt-2">
                            <div class="form-group">
                                <label for="option1">Posted By</label>
                                {% render_field form.posted_by class="form-control" %}
                            </div>
                        </div>
                        <input type="hidden" value="{{request.user.pk}}" name="posted_by">
                    </div>
                    <div class="row">
                        <hr />
                        <div class="col">
                            <button type="submit" class="btn btn-info">Submit</button>
                            <a href="{% url 'users:available_polls'%}" class="btn btn-info mx-2 ">Available Polls</a>
                            <a href="{% url 'users:available_questions'%}" class="btn btn-info mx-2">Available Questions</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mysite/users/templates/users/create_poll_quiz.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Create Question{% endblock %}
{% block content %}
{{form.errors}}
<div class="row">
    <div class="col-lg-12 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create A Question</h3>
            </div>
            <form action="" method="POST">
              {% csrf_token %}
                <div class="panel-body">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="name" class="mb-2">Question:</label>
                                {% render_field form.question_text class="form-control"  required=True%}
                                
                            </div>
                        </div>
                        
                    <div class="row mt-2">
                        <hr />
                        <div class="col">
                            <button type="submit" class="btn btn-info">Submit</button>
                            <a href="{% url 'users:available_polls'%}" class="btn btn-info ">Available Polls</a>

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mysite/users/templates/users/delete_poll_name.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Create Quiz{% endblock %}

{% block content %}
<div class="card border-info mb-3 mt-4" style="width: 25rem;">
    <div class="card-body justify-content-end">
        <div class="card-header bg-transparent border-info mb-3">Delete This Question <span style='font-size:20px;'>&#128071;</span></div>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ poll.name }}"?</p>
            {{ form }}
            <input class="btn btn-warning" type="submit" value="Confirm">
        </form>
  </div>
{% endblock %}

mysite/users/templates/users/edit_profile.html
{% extends 'polls/index.html' %}
{% load widget_tweaks %}


{% block content %}
      <div class="card border-info mb-3 mt-4" style="width: 35rem;">
        <div class="card-body">
            <div class="card-header bg-transparent border-info mb-3">Update Profile
                <span style='font-size:20px;'>&#128071;</span></div>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit">Update</button>
          </form>
          <div class="card-footer bg-transparent border-info mt-2">
          <a href="{% url 'users:login'%}" class="card-link">Already have an account 
            <span style='font-size:20px;'>&#128073;</span></a>
        </div>
      </div>
{% endblock %}

mysite/users/templates/users/edit_questions.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Create Quiz{% endblock %}

{% block content %}
<div class="card border-info mb-3 mt-4" style="width: 25rem;">
    <div class="card-body justify-content-end">
        <div class="card-header bg-transparent border-info mb-3">Edit the Question <span style='font-size:20px;'>&#128071;</span></div>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button class="btn btn-primary" type="submit">Update</button>
      </form>
  </div>
{% endblock %}

mysite/users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

mysite/users/templates/users/register.html
{% extends 'polls/index.html' %}
{% load widget_tweaks %}


{% block content %}
      <div class="card border-info mb-3 mt-4" style="width: 35rem;">
        <div class="card-body">
            <div class="card-header bg-transparent border-info mb-3">Register Here <span style='font-size:20px;'>&#128071;</span></div>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit">Register</button>
          </form>
          <div class="card-footer bg-transparent border-info mt-2">
          <a href="{% url 'users:login'%}" class="card-link">Already have an account <span style='font-size:20px;'>&#128073;</span></a>
        </div>
      </div>
{% endblock %}

mysite/users/templates/users/vote.html
{% extends "base.html" %}

{% block title %}Vote{% endblock %}

{% block content %}
<h3 class="panel-title mt-5">Cast Your Vote</h3>
<div class="row row-cols-1 row-cols-md-3 g-4">
    
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title mb-3">{{ poll.question }}</h5>
                <form action="{% url 'users:vote' poll.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="radio">
                            <div class="mt-1 mb-1">
                                <label>
                                    <input type="radio" name="poll" value="option1">
                                    {{ poll.option_one }}
                                </label> &nbsp;
                            </div>
                            <div class="mt-1 mb-2">
                                <label>
                                    <input type="radio" name="poll" value="option2">
                                    {{ poll.option_two }}
                                </label> &nbsp;
                            </div>
                            <div class="mt-1 mb-2">
                                <label>
                                    <input type="radio" name="poll" value="option3">
                                    {{ poll.option_three }}
                                </label> &nbsp;
                            </div>
                        </div>
                    </div>
                    <hr />
                    {% if voted %}
                    You voted - {{voted.selected_option}}
                    {%else%}
                    <button type="submit" class="btn btn-info mx-2">
                        Submit
                    </button>
                    {%endif%}
                    <a href="{% url 'users:results' poll.id%}" class="btn btn-success my-2">View Results</a> &nbsp;
                </form>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/users/voters.html
{% extends 'base.html'%}

{% block content%}
<form action="{% url 'users:votersearch' %}" method="GET" class="d-flex mb-2">
  <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search"  name="search_voter">
  <button class="btn btn-outline-success" type="submit">Search Voter</button>
</form>
<table class="table table-bordered mt-3">
  <thead>
    <tr class="table-info">
      <th scope="col">User Id</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      {%if voted%}
      <th scope="col">Votes Cast</th>
      {%endif%}
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for user  in users %}
    <tr class="table-info">
      <th scope="row">{{user.id}}</th>
      <td class="table-info">{{user.first_name}}</td>
      <td class="table-info">{{user.last_name}}</td>
      <td class="table-info">{{user.email}}</td>

      {% if vote in votes%}
      <td class="table-info">{{votes}}</td>
      {%endif%}
      

      <td class="table-info">
        <a href="{% url 'users:edit_profile'%}">Edit</a>
      </td>
    </tr>
    
    {%endfor%}
  </tbody>
</table>
{% endblock%}